sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /pr2/voxel_grid/points #replace with /pr2/3d_map/points when running your own code
    max_range: 2.5 #default value: 2.5
    frame_subsample: 1 #default value: 1
    point_subsample: 1 #default value: 1
    padding_offset: 0.01 #default value: 0.01
    padding_scale: 1.0 #default value: 1.0
    #filtered_cloud_topic: filtered_cloud #Use only for debugging
